#include "base.h"

namespace NLP {

  const std::string PREFACE_HEADER = "# this file was generated by :";

  /**
   * read_preface.
   * Reads a preface from the input stream and stores it in the referenced
   * preface string. The preface is expected to be a series of lines at the very
   * start of the file that begin with #. A blank line indicates the end of
   * the preface.
   */
  void read_preface(const std::string &uri, std::istream &input,
      std::string &preface, uint64_t &nlines, const bool required) {
    char c = input.peek();
    if (c != '#') {
      if (required)
        throw IOException("file does not start with the expected preface", uri);
    }
    else {
      std::string buffer;
      while (getline(input, buffer)) {
        ++nlines;
        if (buffer.length() == 0)
          break;
        if (buffer[0] != '#')
          throw IOException("line within preface that does not start with #", uri);
        if (buffer.find(PREFACE_HEADER) == 0)
          continue;

        preface += buffer;
        preface += '\n';
      }
    }
  }

  /**
   * create_preface.
   * Given a program invocation (argc, argv), writes out the invocation
   * to the referenced preface string, prefixing all lines with # and ending
   * with a blank line. This string is then expected to be output first
   * into a generated file.
   */
  void create_preface(int argc, char **argv, std::string &preface) {
    preface = PREFACE_HEADER;
    preface += "\n#  ";
    preface += argv[0];
    for (int i = 1; i < argc; ++i) {
      preface += ' ';
      preface += argv[i];
    }
    preface += '\n';
  }
}
