BINARIES = bin/test bin/train_ner
CORE_OBJECTS = src/lib/base.o src/lib/version.o src/lib/input.o
PORT_OBJECTS = src/lib/port/colour.o src/lib/port/unix_common.o
IO_OBJECTS = src/lib/io/reader_factory.o src/lib/io/reader_conll.o

CONFIG_OBJECTS = src/lib/config/base.o src/lib/config/group.o src/lib/config/option.o

CRF_OBJECTS = src/lib/word.o src/lib/lexicon.o src/lib/tagset.o src/lib/crf/tagger.o src/lib/crf/ner.o

FEATURE_OBJECTS = src/lib/crf/features/attributes.o src/lib/crf/features/feature_types.o \
		  src/lib/crf/features/feature_gen.o src/lib/crf/features/type.o

REQUIRED_OBJECTS = $(IO_OBJECTS) $(CRF_OBJECTS) $(FEATURE_OBJECTS)

.PHONY: all deps clean

all: $(BINARIES)

clean:
	find . -name "*.o" | xargs rm

deps:
	src/scripts/depends "$(CXX) -MM $(INCLUDE)" `find src -name '*.cc' | grep -v ^src/lib/port` $(PORT_OBJECTS:%.o=%.cc) > Makefile.deps

%.h.gch: %.h
	$(CXX) -x c++-header $(CXXFLAGS) -o $@ $<

bin/test: src/main/test.o $(CORE_OBJECTS) $(PORT_OBJECTS) $(CONFIG_OBJECTS) $(REQUIRED_OBJECTS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^

bin/train_ner: src/main/train_ner.o $(CORE_OBJECTS) $(PORT_OBJECTS) $(CONFIG_OBJECTS) $(REQUIRED_OBJECTS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^

