BINARIES = bin/test
CORE_OBJECTS = src/lib/version.o
PORT_OBJECTS = src/lib/port/colour.o

CONFIG_OBJECTS = src/lib/config/base.o src/lib/config/group.o src/lib/config/option.o

.PHONY: all deps clean

all: $(BINARIES)

clean:
	find . -name "*.o" | xargs rm

deps:
	src/scripts/depends "$(CXX) -MM $(INCLUDE)" `find src -name '*.cc' | grep -v ^src/lib/port` $(PORT_OBJECTS:%.o=%.cc) > Makefile.deps

%.h.gch: %.h
	$(CXX) -x c++-header $(CXXFLAGS) -o $@ $<

bin/test: src/main/test.o $(CORE_OBJECTS) $(PORT_OBJECTS) $(CONFIG_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^

